[tool.poetry]
name = "reflection-agent"
version = "0.1.0"
description = "Reflection-Agent project for the Udemy LangGraph course"
authors = ["Abtin Zandi <abtinzandi@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
python-dotenv = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.9.0"]
build-backend = "poetry.core.masonry.api"
